<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.1.0</Version>
    <Authors>FrameFlux</Authors>
    <RepositoryUrl>https://github.com/wobushiafa/FrameFlux</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <EnablePackageValidation>true</EnablePackageValidation>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.local.props"
          Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.props')" />
</Project>
