<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <FrameFluxCopyNativeAssets>true</FrameFluxCopyNativeAssets>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FrameFlux.Wpf\FrameFlux.Wpf.csproj" />
    <ProjectReference Include="..\..\src\FrameFlux.FFmpeg\FrameFlux.FFmpeg.csproj" />
  </ItemGroup>
</Project>
