<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <ApplicationId>com.frameflux.demo</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FrameFlux.Demo.Avalonia\FrameFlux.Demo.Avalonia.csproj" />
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
  </ItemGroup>
  <ItemGroup>
    <AndroidNativeLibrary Include="..\..\native\artifacts\runtimes\android-arm\native\*.so"
                          Link="lib\armeabi-v7a\%(Filename)%(Extension)" />
    <AndroidNativeLibrary Include="..\..\native\artifacts\runtimes\android-arm64\native\*.so"
                          Link="lib\arm64-v8a\%(Filename)%(Extension)" />
    <AndroidNativeLibrary Include="..\..\native\artifacts\runtimes\android-x86\native\*.so"
                          Link="lib\x86\%(Filename)%(Extension)" />
    <AndroidNativeLibrary Include="..\..\native\artifacts\runtimes\android-x64\native\*.so"
                          Link="lib\x86_64\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
